accountings/urls.py
# URL relacionandas aos usuários
from django.urls import path
from . import views

urlpatterns = [
    path('contabilidades/', views.AccountingsListView.as_view(), name='accountings_list'),
    path('contabilidades/novacontabilidade/', views.NewAccountingCreateView.as_view(), name='create_accounting'),
    path('contabilidades/<int:pk>/update/', views.AccountingUpdateView.as_view(), name='update_accounting'), 
    # path('sistemas/<int:pk>/delete/', views.ErpDeleteView.as_view(), name='erp_delete'),
]

api/urls.py
from django.urls import path
from . import views
from api.viewapiteste import ImportItemTestingView, ClientItemTestingView, ClientOneItemTestingView
from api.view_user import LoginView
from api.view_import import UploadZipView

urlpatterns = [
    path('v1/enviar/', views.ImportItemView.as_view(), name='items-imported-client-view'),
    path('v1/receber/', views.ClientItemView.as_view(), name='items-client-view'),
    path('v1/consultar/<str:code>', views.ClientOneItemView.as_view(), name='items-client-view-code'),
    
    path('v2/enviar/', views.ImportItemV2View.as_view(), name='items-imported-client-view-v2'),
    path('v2/receber/', views.ClientItemV2View.as_view(), name='items-client-view-v2'),
    
    path('test/enviar/', ImportItemTestingView.as_view(), name='test-items-imported-client-view'),
    path('test/receber/', ClientItemTestingView.as_view(), name='test-items-client-view'),    
    path('test/consultar/<str:code>', ClientOneItemTestingView.as_view(), name='test-items-client-view-code'),   
    
    path('v1/login/', LoginView.as_view(), name='api-login'),
    # Recebe o arquivo que será enviado através do extrator do XML
    path('v1/upload-zip/', UploadZipView.as_view(), name='upload-zip'),
    path('v1/process-xml/', views.ProcessZipView.as_view(), name='upload-zip-xml'),
    path('v1/process-sped/', views.ProcessSPED.as_view(), name='upload-zip-sped'),
    path('v1/generate-group-csv/<str:code>', views.GenerateCSVGroup.as_view(), name='generate-reg0000-csv'),
    path('v1/generate-detail-csv/<str:code>', views.GenerateCSVDetail.as_view(), name='generate-reg0000d-csv'),
    path('v1/save-xml-sped/', views.SaveFilesDefinitely.as_view(), name='save-xml-sped'),
    
    
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home.views import HomeView, SearchResultsView, SelectModuleView, SetActiveModuleView
from clients.views import CitySearchView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('accounts.urls')),
    path('', include('erp.urls')),
    path('', include('clients.urls')),
    path('', include('items.urls')),
    path('', include('impostos.urls')),
    path('', include('tasks.urls')),
    path('', include('accountings.urls')),
    path('', include('notifications.urls')),
    path('', include('cattles.urls')),
    path('', include('shopsim.urls')),
    path('', include('pricing.urls')),
    path('', HomeView.as_view(), name='home'),
    path('search/', SearchResultsView.as_view(), name='search'),
    path('select-module/<str:module_key>/', SetActiveModuleView.as_view(), name='set_active_module'),
    path('select-module/', SelectModuleView.as_view(), name='select_module'),
    path('ajax/cities/', CitySearchView.as_view(), name='city_search'),    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountings/models.py
from django.db import models
from auditlog.registry import auditlog
from clients.models import Cities

class Accounting(models.Model):
    name = models.CharField(max_length=255)
    city = models.ForeignKey(Cities, on_delete=models.SET_NULL, null=True, blank=True)
    email = models.CharField(max_length=255)
    phone = models.CharField(max_length=50)
    contact = models.CharField(max_length=255)

    def __str__(self):
        return self.name

auditlog.register(Accounting)

accountings/forms.py
from django import forms
from clients.models import Cities
from .models import Accounting

class AccountingForm(forms.ModelForm):
    class Meta:
        model = Accounting
        fields = ['name', 'city', 'email', 'phone', 'contact']  
        
    def __init__(self, *args, **kwargs):
        super(AccountingForm, self).__init__(*args, **kwargs)
        # Ordena o campo 'city' pelo nome
        self.fields['city'].queryset = Cities.objects.all().order_by('nome') 

accountings/views.py
from rolepermissions.decorators import has_role_decorator
from django.shortcuts import render, redirect
from urllib.parse import urlencode
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy, path
from .models import Accounting
from .forms import AccountingForm

@method_decorator(login_required(login_url='login'), name='dispatch')
class AccountingsListView(ListView):
    model = Accounting
    template_name = 'list_accountings.html'
    context_object_name = 'accountings'

@method_decorator(has_role_decorator(['administrador', 'gerente']), name='dispatch')    
class NewAccountingCreateView(CreateView):
    model = Accounting
    form_class = AccountingForm
    template_name = 'create_accounting.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        message = self.request.GET.get('success')
        context['message'] = message   
        return context       
    
    def get_success_url(self):
        success_url = reverse_lazy('create_accounting')  # Assuming you have a URL named 'contabilidades'
        message = urlencode({'success': 'Contabilidade criada com sucesso!'})  # URL-encode message for safety
        return f"{success_url}?{message}"

    def form_valid(self, form):
        self.object = form.save()
        return redirect(self.get_success_url())   
   
@method_decorator(login_required(login_url='login'), name='dispatch')
# @method_decorator(has_role_decorator(['administrador', 'gerente']), name='dispatch')    
class AccountingUpdateView(UpdateView):
    model = Accounting
    form_class = AccountingForm
    template_name = 'update_accounting.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        accounting = self.get_object()
        context['city'] = accounting.city   
        return context 
    
    def get_success_url(self):
        return reverse_lazy('update_accounting', kwargs={'pk': self.object.pk}) 

accountings/templates/create_accounting.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    <h4>Nova Contabilidade</h4>
    <span>Cadastrar uma nova contabilidade</span>
{% endblock title %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'accountings_list' %}">Contabilidade</a>
    </li>
    <li class="breadcrumb-item"><a href="#!">Nova Contabilidade</a>
    </li>
{% endblock breadcrumb %}

{% block customcss %}
    <!-- Select 2 css -->
    <link rel="stylesheet" href="{% static 'bower_components/select2/css/select2.min.css' %}?{% now "U" %}">
{% endblock customcss %}



{% block content %}
<div class="row">
    <div class="col-sm-12">
        <!-- Product edit card start -->
        <div class="card">
            <div class="card-header">
                <h5>Dados da Contabilidade</h5>
            </div>
            <div class="card-block">
                {% if message %}
                    <div class="alert alert-success border-success">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <i class="icofont icofont-close-line-circled"></i>
                        </button>
                        {{ message }}
                    </div>                
                {% endif %}                
                <div class="row">
                    <div class="col-sm-12">
                        <form class="md-float-material card-block"  method="POST" id="form-create-user">
                            {% csrf_token %}
                            <div class="row">
                                <label class="col-sm-4 col-lg-2 col-form-label">Nome</label>
                                <div class="col-sm-8 col-lg-10">
                                    <span class="messages text-danger">{{ form.name.errors }}</span>
                                    <div class="input-group">
                                        {{ form.name|add_class:"form-control"|attr:"placeholder:Nome da Contabilidade" }}
                                    </div>
                                </div>                                    
                            </div>
                            <div class="row">
                                <label class="col-sm-4 col-lg-2 col-form-label">Contato</label>
                                <div class="col-sm-8 col-lg-10">
                                    <span class="messages text-danger">{{ form.contact.errors }}</span>
                                    <div class="input-group">
                                        {{ form.contact|add_class:"form-control"|attr:"placeholder:Pessoa para contato" }}
                                    </div>
                                </div>                                    
                            </div>                            
                            <div class="row">
                                <label class="col-sm-4 col-lg-2 col-form-label">Cidade</label>
                                <div class="col-sm-8 col-lg-10">
                                    <span class="messages text-danger">{{ form.city.errors }}</span>
                                    <div class="input-group">
                                        <select class="form-control" id="id_city" name="city" required>
                                        </select>
                                    </div>                                                                        
                                    
                                </div>
                                <span class="md-line"></span>
                            </div>    
                            <div class="row">
                                <label class="col-sm-4 col-lg-2 col-form-label">E-mail</label>
                                <div class="col-sm-8 col-lg-10">
                                    <span class="messages text-danger">{{ form.email.errors }}</span>
                                    <div class="input-group">
                                        {{ form.email|add_class:"form-control"|attr:"placeholder:Email da contabilidade"|attr:"type:Email" }}
                                    </div>
                                </div>                                    
                            </div>  
                            <div class="row">
                                <label class="col-sm-4 col-lg-2 col-form-label">Telefone</label>
                                <div class="col-sm-8 col-lg-10">
                                    <span class="messages text-danger">{{ form.phone.errors }}</span>
                                    <div class="input-group">
                                        {{ form.phone|add_class:"form-control telphone_with_code"|attr:"placeholder:(99) 99999-9999"|attr:"data-mask:(99) 99999-9999" }}
                                    </div>
                                </div>                                    
                            </div>                                                                                                                                                                                                
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="text-center m-t-20">
                                        <input type="submit" onClick="showLoading('form-create-user')" value="Salvar" class="btn btn-primary waves-effect waves-light m-r-10" id="btn-save">
                                        <button type="button" class="btn btn-warning waves-effect waves-light">Cancelar
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Product edit card end -->
    </div>
</div>
{% endblock %}


{% block anotherjs %}
    <!-- Masking js -->
    <script src="{% static 'assets/pages/form-masking/inputmask.js' %}"></script>
    <script src="{% static 'assets/pages/form-masking/jquery.inputmask.js' %}"></script>
    <script src="{% static 'assets/pages/form-masking/autoNumeric.js' %}"></script>
    <script src="{% static 'assets/pages/form-masking/form-mask.js' %}?{% now "U" %}"></script>
    <!-- Select 2 js -->
    <script type="text/javascript" src="{% static 'bower_components/select2/js/select2.full.min.js' %}"></script>    

    <script>

        $(document).ready(function() {            

            // Inicializando o Select2
            $('#id_city').select2({
                ajax: {
                    url: '{% url "city_search" %}',
                    dataType: 'json',
                    delay: 250,
                    data: function (params) {
                        return {
                            q: params.term
                        };
                    },
                    processResults: function (data) {
                        return {
                            results: data
                        };
                    },
                    cache: true
                },
                minimumInputLength: 1,
                placeholder: 'Selecione a cidade',
                allowClear: true,
                language: {
                    inputTooShort: function () {
                        return 'Por favor, insira 1 ou mais caracteres';
                    },
                    noResults: function () {
                        return 'Nenhum resultado encontrado';
                    },
                    searching: function () {
                        return 'Procurando...';
                    }
                }                
            });         

        });        
 
             
             
      </script>      
{% endblock anotherjs %}

accountings/templates/list_accountings.html
{% extends "base.html" %}
{% load static %}
{% load accounting_permissions %}

{% block title %}
    <h4>Contabilidade</h4>
    <span>Listagem de contabilidades que os clientes utilizam</span>
{% endblock title %}

{% block customcss %}
    <!-- Data Table Css -->
    <link rel="stylesheet" type="text/css" href="{% static 'bower_components/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/pages/data-table/css/buttons.dataTables.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bower_components/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}">  
{% endblock customcss %}



{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="#!">Contabilidade</a>
    </li>
{% endblock breadcrumb %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <!-- Zero config.table start -->
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-lg-8">
                        <h5>Lista de Contabilidades</h5>
                        <span>Lista dos contabilidades cadastradas no sistema.</span>                        
                    </div>
                    {% if user|has_any_role:"gerente,administrador" %}
                    <div class="col-lg-4">
                        <div class="text-right m-b-20">
                            <a href="{% url 'create_accounting' %}" type="button" class="btn btn-primary waves-effect waves-light" >
                                <i class="icofont icofont-plus-circle"></i>
                                Nova Contabilidade
                            </a>
                        </div>                         
                    </div>
                    {% endif %}
            </div>
            <div class="card-block">
                <div class="dt-responsive table-responsive">
                    <table id="simpletable" class="table table-striped table-bordered nowrap">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th class="text-center">Nome</th>
                            <th class="text-center">Cidade</th>
                            <th class="text-center">Telefone</th>
                            <th class="text-center">Ação</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% if accountings %}
                                {% for accounting in accountings %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td class="text-center">{{ accounting.name }}</td>
                                        <td class="text-center">{{ accounting.city }} - {{ accounting.city.uf_estado }}</td>
                                        <td class="text-center">{{ accounting.phone }}</td>
                                        <td class="text-center">
                                            <a href="{% url 'update_accounting' accounting.pk %}" type="button" class="btn btn-primary waves-effect waves-light text-white">
                                                <i class="icofont icofont-ui-edit"></i>
                                            </a> 
                                        </td>
                                    </tr>                                    
                                {% endfor %}
                            {% endif %}
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- Zero config.table end -->
    </div>
</div>
{% endblock content %}

{% block anotherjs %}
<!-- data-table js -->
<script src="{% static 'bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'bower_components/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'bower_components/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'bower_components/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>
<script src="https://cdn.datatables.net/plug-ins/1.13.1/i18n/pt_BR.json"></script>

<script>
    $(document).ready(function() {
        $('#simpletable').DataTable({
            language: {
                url: '//cdn.datatables.net/plug-ins/2.0.7/i18n/pt-BR.json',
            },
        });      
    });
</script>
{% endblock anotherjs %}

accountings/templates/update_accounting.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load accounting_permissions %}

{% block title %}
    <h4>Editar Contabilidade</h4>
    <span>Editar dados de uma contabilidade</span>
{% endblock title %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'accountings_list' %}">Contabilidade</a>
    </li>
    <li class="breadcrumb-item"><a href="#!">Editar Contabilidade</a>
    </li>
{% endblock breadcrumb %}

{% block customcss %}
    <!-- Select 2 css -->
    <link rel="stylesheet" href="{% static 'bower_components/select2/css/select2.min.css' %}?{% now "U" %}">
{% endblock customcss %}



{% block content %}
<div class="row">
    <div class="col-sm-12">
        <!-- Product edit card start -->
        <div class="card">
            <div class="card-header">
                <h5>Dados da Contabilidade</h5>
            </div>
            <div class="card-block">
                {% if message %}
                    <div class="alert alert-success border-success">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <i class="icofont icofont-close-line-circled"></i>
                        </button>
                        {{ message }}
                    </div>                
                {% endif %}                
                <div class="row">
                    <div class="col-sm-12">
                        {% if user|has_any_role:"gerente,administrador" %} 
                        <form class="md-float-material card-block"  method="POST" id="form-create-user">
                        {% endif %}
                            {% csrf_token %}
                            <div class="row">
                                <label class="col-sm-4 col-lg-2 col-form-label">Nome</label>
                                <div class="col-sm-8 col-lg-10">
                                    <span class="messages text-danger">{{ form.name.errors }}</span>
                                    <div class="input-group">
                                        {{ form.name|add_class:"form-control"|attr:"placeholder:Nome da Contabilidade" }}
                                    </div>
                                </div>                                    
                            </div>
                            <div class="row">
                                <label class="col-sm-4 col-lg-2 col-form-label">Contato</label>
                                <div class="col-sm-8 col-lg-10">
                                    <span class="messages text-danger">{{ form.contact.errors }}</span>
                                    <div class="input-group">
                                        {{ form.contact|add_class:"form-control"|attr:"placeholder:Pessoa para contato" }}
                                    </div>
                                </div>                                    
                            </div>                            
                            <div class="row">
                                <label class="col-sm-4 col-lg-2 col-form-label">Cidade</label>
                                <div class="col-sm-8 col-lg-10">
                                    <span class="messages text-danger">{{ form.city.errors }}</span>
                                    <div class="input-group">
                                        <select class="form-control" id="id_city" name="city" required>
                                            <option value="{{ city.id }}">{{ city.nome }} - {{ city.uf_estado }}</option>
                                        </select>
                                    </div>                                                                        
                                    
                                </div>
                                <span class="md-line"></span>
                            </div>    
                            <div class="row">
                                <label class="col-sm-4 col-lg-2 col-form-label">E-mail</label>
                                <div class="col-sm-8 col-lg-10">
                                    <span class="messages text-danger">{{ form.email.errors }}</span>
                                    <div class="input-group">
                                        {{ form.email|add_class:"form-control"|attr:"placeholder:Email da contabilidade"|attr:"type:Email" }}
                                    </div>
                                </div>                                    
                            </div>  
                            <div class="row">
                                <label class="col-sm-4 col-lg-2 col-form-label">Telefone</label>
                                <div class="col-sm-8 col-lg-10">
                                    <span class="messages text-danger">{{ form.phone.errors }}</span>
                                    <div class="input-group">
                                        {{ form.phone|add_class:"form-control telphone_with_code"|attr:"placeholder:(99) 99999-9999"|attr:"data-mask:(99) 99999-9999" }}
                                    </div>
                                </div>                                    
                            </div>   
                            {% if user|has_any_role:"gerente,administrador" %}                                                                                                                                                                                             
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="text-center m-t-20">
                                        <input type="submit" onClick="showLoading('form-create-user')" value="Salvar" class="btn btn-primary waves-effect waves-light m-r-10" id="btn-save">
                                        <button type="button" class="btn btn-warning waves-effect waves-light">Cancelar
                                        </button>
                                    </div>
                                </div>
                            </div>
                            
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <!-- Product edit card end -->
    </div>
</div>
{% endblock %}


{% block anotherjs %}
    <!-- Masking js -->
    <script src="{% static 'assets/pages/form-masking/inputmask.js' %}"></script>
    <script src="{% static 'assets/pages/form-masking/jquery.inputmask.js' %}"></script>
    <script src="{% static 'assets/pages/form-masking/autoNumeric.js' %}"></script>
    <script src="{% static 'assets/pages/form-masking/form-mask.js' %}?{% now "U" %}"></script>
    <!-- Select 2 js -->
    <script type="text/javascript" src="{% static 'bower_components/select2/js/select2.full.min.js' %}"></script>    

    <script>

        $(document).ready(function() {            

            // Inicializando o Select2
            $('#id_city').select2({
                ajax: {
                    url: '{% url "city_search" %}',
                    dataType: 'json',
                    delay: 250,
                    data: function (params) {
                        return {
                            q: params.term
                        };
                    },
                    processResults: function (data) {
                        return {
                            results: data
                        };
                    },
                    cache: true
                },
                minimumInputLength: 1,
                placeholder: 'Selecione a cidade',
                allowClear: true,
                language: {
                    inputTooShort: function () {
                        return 'Por favor, insira 1 ou mais caracteres';
                    },
                    noResults: function () {
                        return 'Nenhum resultado encontrado';
                    },
                    searching: function () {
                        return 'Procurando...';
                    }
                }                
            });    
            
        });        
 
             
             
      </script>      
{% endblock anotherjs %}